// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbyPhwDs-kFHJYDmnI-mqTN5h2YGtcdIA',
    appId: '1:761279766095:web:c608796fc145f2dfebd43a',
    messagingSenderId: '761279766095',
    projectId: 'fresh-day-dairy',
    authDomain: 'fresh-day-dairy.firebaseapp.com',
    storageBucket: 'fresh-day-dairy.appspot.com',
    measurementId: 'G-NR4Z54DMZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr1z_01NAgw5-7FQHd6yoJt1ju7uZAEis',
    appId: '1:761279766095:android:8bce15cf30edc440ebd43a',
    messagingSenderId: '761279766095',
    projectId: 'fresh-day-dairy',
    storageBucket: 'fresh-day-dairy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL2n2iClYoBtui5IZTTdflKx8JuVHLkgA',
    appId: '1:761279766095:ios:f6d3240351559df0ebd43a',
    messagingSenderId: '761279766095',
    projectId: 'fresh-day-dairy',
    storageBucket: 'fresh-day-dairy.appspot.com',
    iosBundleId: 'com.example.freshDayDairyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL2n2iClYoBtui5IZTTdflKx8JuVHLkgA',
    appId: '1:761279766095:ios:f6d3240351559df0ebd43a',
    messagingSenderId: '761279766095',
    projectId: 'fresh-day-dairy',
    storageBucket: 'fresh-day-dairy.appspot.com',
    iosBundleId: 'com.example.freshDayDairyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbyPhwDs-kFHJYDmnI-mqTN5h2YGtcdIA',
    appId: '1:761279766095:web:00db48a6402dcf04ebd43a',
    messagingSenderId: '761279766095',
    projectId: 'fresh-day-dairy',
    authDomain: 'fresh-day-dairy.firebaseapp.com',
    storageBucket: 'fresh-day-dairy.appspot.com',
    measurementId: 'G-HPCQ78R6GX',
  );
}
